[package]
name = "brail-capture"
version.workspace = true
edition.workspace = true

[dependencies]
brail-core.workspace = true
brail-hardware.workspace = true
windows.workspace = true
windows-core.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
